### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by botshake** [TheCyb3rAlpha/BobTheSmuggler#3]
Hi,

All works well, except when I try to open a generated html page. It shows blank page.
I created it with this: python BobTheSmuggler.py -i C:\PROJECTS\msg.exe -f test.html -o msg.zip -t png -png C:\PROJECTS\Screenshot.png

My image is hosted online (not on cdn).

Did I do anything wrong? Please help :)

**Comment by TheCyb3rAlpha** [comment]
Hi @bostjan39,

Apologies for the delayed response. Been busy with the work. 
Please check debugger console, you should be getting CORS related error. As the JS code sends a XHR request, CORS needs to be enabled on your server for this to work. Otherwise, the HTML page won't load the JS code.
